name: gpbackup_go_build_and_test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened, edited, ready_for_review ]

jobs:

  build_and_unit_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        path: go/github.com/apache/cloudberry-gpbackup

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.4

    - name: Set GOPATH
      run: |
        echo "GOPATH=$GITHUB_WORKSPACE/go" >> $GITHUB_ENV
        echo "$GITHUB_WORKSPACE/go/bin" >> $GITHUB_PATH

    - name : 查看go信息
      run: |
        echo "查看go信息"
        echo $GOPATH
        which go
        echo "###################################################################"
        go env GOPATH
        echo "###################################################################"
        ls $(go env GOPATH)/bin
        echo "###################################################################"
        go env GOBIN

    - name: Dependencies
      run: |
        cd ${GOPATH}/pkg/mod/github.com/cloudberrydb/gpbackup
        make depend

    - name: Build
      run: |
        cd ${GOPATH}/pkg/mod/github.com/cloudberrydb/gpbackup
        make build

    - name: Unit Test
      run: |
        cd ${GOPATH}/pkg/mod/github.com/cloudberrydb/gpbackup
        make test
