name: build_and_unit_test

on:
  push:
    branches: [ test-ci ]
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize, reopened, edited, ready_for_review ]

jobs:

  build_and_unit_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: set ssh
      run: git config --global --add url."git@github.com:".insteadOf "https://github.com/"
    - name: Set Environment
      run: go get https://github.com/greenplum-db/gpbackup/
